### ISSUE TITLE
Broken reference to networking-release on bosh.io

### ISSUE THREAD

**Issue by henryaj** [cloudfoundry/networking-release#9]
Hi,

The latest version of http://bosh.io/releases/github.com/cf-platform-eng/networking-boshrelease?all=1 seems to be broken - or rather, it downloads version 6 of the networking-boshrelease (which is missing e.g. the `port_forwarding` job). 

Henry && Alvaro

**Comment by dpb587-pivotal** [comment]
This repository was moved from https://github.com/cf-platform-eng/networking-boshrelease, and bosh.io is no longer updating from that old URL. Try updating your pipelines to pull from https://bosh.io/releases/github.com/cloudfoundry/networking-release instead.

@cppforlife, is there a way old release pages can be marked as discontinued to avoid this sort of confusion?
